### ISSUE TITLE
Add a drop down menu to the fetch tool.

### ISSUE THREAD

**Issue by eddyod** [ActiveBrainAtlasPipeline/neuroglancer#12]
We want the annotations with the numbers and locations but we also want to align them. The reason you can't align an annotation layer is simply because it is not associated with an animal so the program at the moment is too dumb to know what to do. We can add a drop down next to the 'Fetch rotation layer for this layer' link. The drop down will contain the list of animals that have centers of mass. 

Instead of a link, we could change it to a drop down and use the onchange or onblur to submit the request.

**Comment by Junjie-Cheng** [comment]
Hi @eddyod ,

I make the selection available, please check the ng_new_fetch folder to see whether it is what we want. I currently hardcoded all the brains and it would be good if we can have a API that returns a list of animals that have centers of mass.

Let me know if I need to make any changes.

**Comment by Junjie-Cheng** [comment]
Hi @eddyod 
I am not sure what the `person_id` and `input_type` refers to - especially what could be the values of these fields: do we have a long list of `person_id` and an input for `input_type`?

If all the alignment methods are based on center of mass, then I suggest that we add in the database a description field for each set of centers of mass. Then we can get the list of sets of centers of mass for specific brain, and the users can simply pick the description that they want.
In terms of UI, the only change will be that there will be another selection element after the brain selection, listing all the COMs related to the brain selected in the first selection element. Please let me know if I misunderstood anything!
