### ISSUE TITLE
Update rotation/translation matrix

### ISSUE THREAD

**Issue by eddyod** [ActiveBrainAtlasPipeline/neuroglancer#2]
The matrices returned by https://activebrainatlas.ucsd.edu/activebrainatlas/alignatlas?animal=junk should match https://activebrainatlas.ucsd.edu/activebrainatlas/alignatlas?animal=DK39

Please test and implement.

**Comment by Junjie-Cheng** [comment]
Hi Ed,
It works pretty fine on my end.
Just need to confirm one thing before I push my commits: Should we only consider `precomputed://https://activebrainatlas.ucsd.edu/data/DK39/neuroglancer_data/atlas_v7` as atlas, or all the URLs with the format `precomputed://https://activebrainatlas.ucsd.edu/data/[SOME_BRAIN]/neuroglancer_data/atlas[*]`

**Comment by eddyod** [comment]
Junjie,
We should only be using the generic first one you mention in the comment above. I started creating those other ones under each brain but they are not necessary at the moment.

**Comment by eddyod** [comment]
This has been dealt with and we are moving onto another issue.
