### ISSUE TITLE
Move fetch auto alignment link

### ISSUE THREAD

**Issue by eddyod** [ActiveBrainAtlasPipeline/neuroglancer#3]
@Junjie-Cheng 

We need to move the fetch auto alignment link from the atlas layer to any other layers. In fact, if should appear in every layer except for the on the atlas is on.

**Comment by Junjie-Cheng** [comment]
Hi @eddyod 
Please check the `/ng_rotate_animals/` version. The button will show as long as the url is precomputed and starts with `https://activebrainatlas.ucsd.edu/data/[Animal Name]/`. The same API was called.

**Comment by eddyod** [comment]
This version is now live.
